# Site settings
title: Misa Redondo
subtitle: Photography
email: misaredondo@gmail.com
description: Contar la historia, registrar el momento y plasmar el recuerdo.
url: "" # the base hostname & protocol for your site
author: Misa Redondo
street_address: Mi Calle 123
city: Culiacán
state: Sinaloa
zip_code: 80000
country: México
phone: +52 667 204 9752

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
  style: compressed
